// todo-vue-monolithic/src/components/note/NoteSearch.vue
<!-- Use for Vue Provide, Inject API Only (issues when do, finish, cancel note)
import { useGlobalStore } from '../../composables';
import { actions } from '../../context/global/reducer';

const { state } = useGlobalStore();

const searchValue = ref('');
const searchPriority = ref(state.priorities.map(v => v.value));
const searchStatus = ref(state.status.map(v => v.value));

const onSearchNote = () => {
    actions.searchNote(searchValue.value, searchPriority.value, searchStatus.value);
}

const onResetNote = () => {
    actions.resetSearchNote();
}
-->

<script setup>
import { onMounted, ref } from 'vue';
import { useStore } from 'vuex';
import { noteActionsType } from '../../store/modules';

const store = useStore();

const searchValue = ref('');
const searchPriority = ref(store.getters.priorities.map(v => v.value));
const searchStatus = ref(store.getters.status.map(v => v.value));

const onSearchNote = () => {
    store.dispatch(noteActionsType.SEARCH_NOTE, { searchValue: searchValue.value, searchPriority: searchPriority.value, searchStatus: searchStatus.value });
}

const onResetNote = () => {
    store.dispatch(noteActionsType.RESET_SEARCH_NOTE);
}

onMounted(() => {
    console.log('Render Note Search');
});
</script>

<template>
    <br />
    <strong>Search Note: </strong> <br />
    <i>Content: </i> <br />
    <input type="text" v-model="searchValue" /> <br />

    <i>Priorities: </i> <br />
    <input type="checkbox" value="Medium" v-model="searchPriority" /> Medium <br>
    <input type="checkbox" value="High" v-model="searchPriority" /> High <br>
    <input type="checkbox" value="Low" v-model="searchPriority" /> Low <br>

    <i>Status: </i> <br />
    <input type="checkbox" value="Todo" v-model="searchStatus" /> Todo <br>
    <input type="checkbox" value="Doing" v-model="searchStatus" /> Doing <br>
    <input type="checkbox" value="Done" v-model="searchStatus" /> Done <br>
    <input type="checkbox" value="Cancel" v-model="searchStatus" /> Cancel <br>

    <input type="button" value="Search" @click="onSearchNote" />
    <input type="button" value="Reset" @click="onResetNote" />
</template>

// todo-react-monolithic/src/components/note/NoteSearch.jsx
import { memo, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { selectors } from '../../store';
import { noteActions } from './slice';

/** Use Context API with Reducer
const { state: { priorities, status }, actions } = useNoteContext();

const [textSearch, setTextSearch] = useState('');
const [prioritiesSearch, setPrioritiesSearch] = useState(priorities.map((v) => v.value));
const [statusSearch, setStatusSearch] = useState(status.map((v) => v.value));
const textSearchRef = useRef(undefined);

const onSearch = () => actions.search({ textSearch, prioritiesSearch, statusSearch });
const onReset = () => {
	actions.resetSearch();
	setTextSearch('');
	setPrioritiesSearch(priorities.map((v) => v.value));
	setStatusSearch(status.map((v) => v.value));
	textSearchRef.current?.focus();
};
*/

const NoteSearch = () => {
	console.log('Render Note Search');

	const priorities = useSelector(selectors.priorities);
	const status = useSelector(selectors.status);
	const dispatch = useDispatch();

	const [textSearch, setTextSearch] = useState('');
	const [prioritiesSearch, setPrioritiesSearch] = useState(priorities.map((v) => v.value));
	const [statusSearch, setStatusSearch] = useState(status.map((v) => v.value));
	const textSearchRef = useRef(undefined);

	const onSearch = () => dispatch(noteActions.searchNote({ textSearch, prioritiesSearch, statusSearch }));
	const onReset = () => {
		dispatch(noteActions.resetSearchNote());
		setTextSearch('');
		setPrioritiesSearch(priorities.map((v) => v.value));
		setStatusSearch(status.map((v) => v.value));
		textSearchRef.current?.focus();
	};
	return (
		<div>
			<br />
			<strong>Search Note: </strong> <br />
			<i>Content: </i> <br />
			<input type="text" ref={textSearchRef} value={textSearch} onChange={(e) => setTextSearch(e.target.value)} /> <br />
			<i>Priorities: </i> <br />
			{priorities.map((priority) => (
				<div key={priority.id}>
					<input
						type="checkbox"
						value={priority.value}
						checked={prioritiesSearch.includes(priority.value)}
						onChange={(e) =>
							setPrioritiesSearch(e.target.checked ? [...prioritiesSearch, priority.value] : prioritiesSearch.filter((v) => v !== priority.value))
						}
					/>
					{priority.value}
				</div>
			))}
			<i>Status: </i> <br />
			{status.map((status) => (
				<div key={status.id}>
					<input
						type="checkbox"
						value={status.value}
						checked={statusSearch.includes(status.value)}
						onChange={(e) => setStatusSearch(e.target.checked ? [...statusSearch, status.value] : statusSearch.filter((v) => v !== status.value))}
					/>
					{status.value}
				</div>
			))}
			<input type="button" value="Search" onClick={onSearch} />
			<input type="button" value="Reset" onClick={onReset} />
		</div>
	);
};

export default memo(NoteSearch);
