// todo-vue-monolithic/src/components/note/NoteList.vue
<!-- Use for Vue Provide, Inject API Only (issues when do, finish, cancel note)
import { useGlobalStore } from '../../composables';
const { state } = useGlobalStore();

const notes = computed(() => state.isSearching ? state.latestSearchNote : state.latestNote);
-->

<script setup>
import { computed, onMounted } from 'vue';
import { useStore } from 'vuex';
import NoteItem from './NoteItem.vue';

const store = useStore()
const notes = computed(() => store.getters.isSearching ? store.getters.latestSearchNote : store.getters.latestNote);

onMounted(() => {
    console.log('Render Note List');
});
</script>

<template>
    <div>
        <br />
        <strong>Note List: </strong>
        <p v-if="!notes">No data available</p>
        <table v-else>
            <thead>
                <tr>
                    <th style="text-align: end">ID</th>
                    <th style="text-align: end">Value</th>
                    <th style="text-align: end">Status</th>
                    <th style="text-align: end">Priority</th>
                    <th style="text-align: end">Created At</th>
                    <th style="text-align: end">Actions</th>
                </tr>
            </thead>
            <tbody>
                <NoteItem v-for="note in notes" :key="note.id" :data="note" />
            </tbody>
        </table>
    </div>
</template>

// todo-react-monolithic/src/components/note/NoteList.jsx
import { memo, useMemo } from 'react';
import { useSelector } from 'react-redux';
import { selectors } from '../../store';
import NoteItem from './NoteItem';
import { useFetchNotes } from './query';

/** Use Context API with Reducer
import { useNoteContext } from '../../hooks';

const { state: { latestNote, latestSearchNote, isSearching } } = useNoteContext();
*/

/** Use for Redux Thunk Only
import { useSelector } from 'react-redux';
import { selectors } from '../../store';

const latestNote = useSelector(selectors.latestNote);
const latestSearchNote = useSelector(selectors.latestSearchNote);
const isSearching = useSelector(selectors.isSearching);
*/

/** Use for RTK Query Only
const { data, isLoading } = useFetchNotesQuery();
const latestSearchNote = useSelector(selectors.latestSearchNote);
const isSearching = useSelector(selectors.isSearching);
const latestNote = useMemo(() => data?.notes || [], [data]);
*/

const NoteList = () => {
	console.log('Render Note List');

	const { data, isLoading } = useFetchNotes();
	const latestSearchNote = useSelector(selectors.latestSearchNote);
	const isSearching = useSelector(selectors.isSearching);
	const latestNote = useMemo(() => data || [], [data]);

	return (
		<div>
			<br />
			<strong>Note List: </strong>
			{isLoading && (
				<p>
					Loading... <br />
				</p>
			)}
			{latestNote?.length === 0 || (latestSearchNote?.length === 0 && isSearching) ? (
				<p>No data available</p>
			) : (
				<table>
					<thead>
						<tr>
							<th style={{ textAlign: 'end' }}>ID</th>
							<th style={{ textAlign: 'end' }}>Value</th>
							<th style={{ textAlign: 'end' }}>Status</th>
							<th style={{ textAlign: 'end' }}>Priority</th>
							<th style={{ textAlign: 'end' }}>Created At</th>
							<th style={{ textAlign: 'end' }}>Actions</th>
						</tr>
					</thead>
					<tbody>
						{!isSearching
							? latestNote.map((note) => <NoteItem key={note.id} data={note} />)
							: latestSearchNote.map((note) => <NoteItem key={note.id} data={note} />)}
					</tbody>
				</table>
			)}
		</div>
	);
};

export default memo(NoteList);
